.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH ARISTA-GTK 1 "July 16, 2009"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NOME
arista-gtk \-  interface gráfica para o Arista Transcoder
.SH SINOPSE
.B arista-gtk
.SH DESCRIÇÃO
Este manual documenta brevemente o comando \fBarista-gtk\fP.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBarista\fP é um conversor multimídia para o Ambiente GNOME que permite
o usuário converter áudio e vídeo para uma vasta variedade de dispositivos.
.PP
.B arista-gtk
fornece uma simples interface para o usuário para o comando \fBarista-transcode\fP.
.PP
.B arista-gtk
foi escrito em Python e GTK+2, e depois de instalar a aplicação
você pode executá-lo a partir do menu \fBAplicativos\fP.
.SH VER TAMBÉM
.BR arista-transcode (1).
.SH AUTOR
arista-gtk foi escrito por Daniel G. Taylor <dan@programmer-art.org>.
.PP
Este manual foi escrito por Alessio Treglia <quadrispro@ubuntu.com>,
para o projeto Ubuntu (e pode ser usado por outros).
.SH TRADUÇÃO E REVISÃO PARA PORTUGUÊS DO BRASIL
Átila Camurça <camurca.home@gmail.com>, Darlildo Lima <darlildo.cefetce@gmail.com>.
